version: '3.3'
volumes:
  data:
services:
  nginx:
    build: ./docker/nginx
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - .:/opt/work
    links:
      - php
    container_name: nginx_Datafodase
    networks:
      - mysql-compose-network
  php:
    build: ./docker/php
    volumes:
      - .:/opt/work
    container_name: php_Datafodase
    networks:
      - mysql-compose-network
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - ./bancodedados/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge